# Generated by Django 2.0.1 on 2018-01-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Enter the name of the task', max_length=200)),
                ('estimated_total_duration', models.IntegerField(blank=True, help_text='How much time (in hours) would you estimate for the task to be completed?', null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[(1, 'Very Important'), (2, 'Important'), (3, 'Not that Important')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
