# Generated by Django 2.0.1 on 2018-01-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20180109_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Very Important'), (2, 'Important'), (3, 'Not that Important')], max_length=1),
        ),
    ]
