# Generated by Django 2.0.1 on 2018-01-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180109_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Very Important'), (2, 'Important'), (3, 'Not that Important')]),
        ),
    ]
